title: vnemana blog
author: vnemana
description: > # this means to ignore newlines until "baseurl:"
test blog

theme: minima
# social links
github_username:  vnemana # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
